site_name: Data stations voor secundair gebruik in de zorg
site_url: https://health-ri.github.io/data-station-specification
repo_url: https://github.com/Health-RI/data-station-specification
theme:
  name: material
  language: 'nl'
  custom_dir: overrides
  font:
    text: Fira Sans
    code: Fira Code
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  palette:
    primary: custom
    accent: custom
  features:
    - content.tooltips
    - header.autohide
    - navigation.footer
    - navigation.indexes
    - navigation.instant.preview
    - navigation.top
    - navigation.tracking
    # - navigation.path
    - toc.integrate
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      auto_append:
        - includes/woordenlijst.md
  - pymdownx.tabbed:
      alternate_style: true
  - tables
plugins:
  - bibtex:
      bib_file: "data-station-specification.bib"
  - glightbox
  - i18n:
      docs_structure: suffix
      languages:
        - locale: nl
          name: Nederlands
          build: true
          default: true
        - locale: en
          name: English
          build: true
          site_name: Data stations for secondary use of health data
          nav_translations:
            # Introduction sections
            Data stations voor secundair gebruik in de zorg: Data station for secondary use of health data
            Inleiding: Introduction
            Scope van de specificatie: Scope of the specification
            Data stations als basis voor interoperabiliteit: Data stations as cornerstone for interoperability
            Leeswijzer: Reader's guide

            # main sections
            Architectuur: Architecture
            Functionele componenten: Functional components
            Implementaties: Implementations

            # sub-sections
            Motivatie: Motivation
            Principes: Principles
            Standaarden: Standards
            Data station: Data station
            Federatief netwerk: Federated network
            PLUGIN: PLUGIN
            KIK-V: KIK-V
  - meta
  - mkdocs-pdf
  - search
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      theme:
        light: kanagawa/fuji
        dark: kanagawa/wave
extra:
  alternate:
    - name: Nederlands
      link: /
      lang: nl
    - name: English
      link: /en/
      lang: en
watch:
  - includes

# Page tree
nav:
  - Inleiding:
    - index.md
    - waarom.md
    - data-stations-als-hoeksteen.md
    - leeswijzer.md
  - Architectuur:
    - architectuur/index.md
    - Use-case DAAMS: architectuur/daams.md
    - Use-case Federated Analytics Portal: architectuur/fap.md
    - Use-case Data station: architectuur/data-station.md
    - Standaarden: architectuur/standaarden.md
  - Functionele componenten:
    - componenten/index.md
    - Data station:
      - componenten/data-station/index.md  
      - Aanleveren: componenten/data-station/aanleveren.md
      - Ingestie: componenten/data-station/ingestie.md
      - Transformeren: componenten/data-station/transformeren.md
    - Federatief netwerk:
      - componenten/federatief-netwerk/index.md
      - Federatieve analyse: componenten/federatief-netwerk/federatieve-analyse.md
      - Federatief leren: componenten/federatief-netwerk/federatief-leren.md
      - Data pooling: componenten/federatief-netwerk/data-pooling.md
  - Implementaties:
    - implementaties/index.md
    - PLUGIN:
      - implementaties/PLUGIN/index.md
      - Architectuur: implementaties/PLUGIN/architectuur.md
    - KIK-V:
      - implementaties/KIK-V/index.md
      - Architectuur: implementaties/PLUGIN/architectuur.md
    - DataSHIELD:
      - implementaties/DataSHIELD/index.md
      - Architectuur: implementaties/DataSHIELD/architectuur.md
  - Discussie:
    - discussie/index.md
    - Primair vs. secundair: discussie/primair-vs-secundair.md
    - Centraal vs. federatief: discussie/centraal-vs-federatief.md
    - Permit vs. request: discussie/permit-vs-request.md
  - Appendix:
    - appendix/index.md
    - Archimate data space: https://health-ri.github.io/data-spaces-archimate/
    - TEHDAS2 HDAB: appendix/tehdas2-hdab.md
    - TEHDAS2 SPE: appendix/tehdas2-spe.md

