site_name: Specificatie van data stations voor secundair gebruik
site_url: https://health-ri.github.io/data-station-specification
repo_url: https://github.com/Health-RI/data-station-specification
theme:
  name: material
  language: 'nl'
  custom_dir: overrides
  font:
    text: Fira Sans
    code: Fira Code
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  palette:
    primary: custom
    accent: custom
  features:
    - header.autohide
    - navigation.footer
    - navigation.indexes
    - navigation.instant.preview
    - navigation.top
    - navigation.tracking
    - navigation.path
    - toc.integrate
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
plugins:
  - glightbox
  - meta
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: nl
          name: Nederlands
          build: true
          default: true
        - locale: en
          name: English
          build: true
          nav_translations:
            # main sections
            Architectuur: Architecture
            Componenten: Components
            Implementaties: Implementations

            # sub-sections
            Motivatie: Motivation
            Principes: Principles
            Standaarden: Standards

  - bibtex:
      bib_file: "data-station-specification.bib"

extra:
  alternate:
    - name: Nederlands
      link: /
      lang: nl
    - name: English
      link: /en/
      lang: en

# Page tree
nav:
  - Home: index.md
  - Architectuur:
    - architectuur/index.md
    - Motivatie: architectuur/motivatie.md
    - Principes: architectuur/principes.md
    - Standaarden: architectuur/standaarden.md
  - Componenten:
    - componenten/index.md
  - Implementaties:
    - implementaties/index.md
